# MTH420 TERM PROJECT

### Standardized Test Score File Processing - Data Challenge

### Scenario 
 
In this scenario, our goal is to process annual assessment scores for a client. “sample-mcas.csv” is an MCAS CSV file in the source format determined by the state of Massachusetts. Before our application can import the data, it needs to be manipulated in accordance with our template. 
 
Assitionally, “sample-mcas-processed.csv” is an example of a transformed output file and there are further specifications on the next page. For this scenario, the only pertinent tests are MCAS ELA, MCAS Math, and MCAS Science.

### Import Standard Python/ Packages

In [44]:
import numpy as np
import scipy as sc
import pandas as pd
import matplotlib as plt
%matplotlib inline

### Read In the .CSV File: "sample-mcas.csv"
Use the pandas read_csv function to import the MCAS data file we will be working with.

In [45]:
sample = pd.read_csv("../../../Desktop/Internship & Job Application Files/Job Application Files/Ellevation Education/sample-mcas  (5) (1) (1) (1).csv")

###  Display a portion of the input DataFrame
This can show us what our input file looks like and confirms that it populated correctly into the DataFrame.

In [46]:
# Display the first 10 rows of the sample (input) DataFrame
sample.head(10)
# list(sample.columns)
# sample[['sasid', 'stugrade', 'eitem1', 'eitem2']]

,district,school,schtype,adminyear,bookletnumber,sasid,grade,stugrade,lastname,firstname,...,mscaleds2010,mscaleds2011,mscaleds2012,esgp2010,esgp2011,esgp2012,msgp2010,msgp2011,msgp2012,summarize
0,DistrictX,5,ES,2013,682515750,1408905,3,3,Smith,John,...,,,,,,,,,,1
1,DistrictX,5,ES,2013,424062353,1020285,3,3,Smith,John,...,,,,,,,,,,1
2,DistrictX,5,ES,2013,582975335,1681155,3,3,Smith,John,...,,,,,,,,,,1
3,DistrictX,5,ES,2013,408171609,1987801,3,3,Smith,John,...,,,,,,,,,,1
4,DistrictX,5,ES,2013,708941361,1351732,3,3,Smith,John,...,,,,,,,,,,1
5,DistrictX,5,ES,2013,522921439,1259640,3,3,Smith,John,...,,,,,,,,,,1
6,DistrictX,5,ES,2013,677904433,1833359,3,3,Smith,John,...,,,,,,,,,,1
7,DistrictX,5,ES,2013,668174183,1624948,3,3,Smith,John,...,,,,,,,,,,1
8,DistrictX,5,ES,2013,797664016,1761110,3,3,Smith,John,...,,,,,,,,,,1
9,DistrictX,5,ES,2013,527527177,1336566,3,3,Smith,John,...,,,,,,,,,,1

In [63]:
ddict = {}
ddict['NCESID'] = []; ddict['StudentTestID'] = []; ddict['StudentLocalID'] = []; ddict['StudentGradeLevel'] = [];
ddict['TestDate'] = []; ddict['TestName'] = []; ddict['TestTypeName'] = []; ddict['TestSubjectName'] = [];
ddict['TestGradeLevel'] = []; ddict['Score1Label'] = []; ddict['Score1Type'] = []; ddict['Score1Value'] = [];
ddict['Score2Label'] = []; ddict['Score2Type'] = []; ddict['Score2Value'] = []; ddict['Score3Label'] = [];
ddict['Score3Type'] = []; ddict['Score3Value'] = []

In [64]:
ddict2 = {}
ddict2['ELA Q1'] = []; ddict2['ELA Q2'] = []; ddict2['ELA Q3'] = []; ddict2['ELA Q4'] = []; ddict2['ELA Q5'] = []
ddict2['MATH Q1'] = []; ddict2['MATH Q2'] = []; ddict2['MATH Q3'] = []; ddict2['MATH Q4'] = []; ddict2['MATH Q5'] = []
ddict2['SCIENCE Q1'] = []; ddict2['SCIENCE Q2'] = []; ddict2['SCIENCE Q3'] = []; ddict2['SCIENCE Q4'] = [];
ddict2['SCIENCE Q5'] = []

In [65]:
# define function for District ID (NCESID)
def id_NCESID(district):
    if district == 'DistrictX':
        return '101010'
    else:
        return '373737'

# define function for TestDate, TestTypeName, and TestSubjectName
def get_TestDate_TestTypeName_TestSubjectName(num_tests):
    if num_tests == 3:
        ddict['TestDate'].append('4/1/2013'); ddict['TestDate'].append('5/1/2013'); ddict['TestDate'].append('6/1/2013')
        ddict['TestTypeName'].append('MCAS ELA'); ddict['TestTypeName'].append('MCAS Math'); ddict['TestTypeName'].append('MCAS Science')
        ddict['TestSubjectName'].append('ELA'); ddict['TestSubjectName'].append('Math'); ddict['TestSubjectName'].append('Science')
    elif num_tests == 2:
        ddict['TestDate'].append('4/1/2013'); ddict['TestDate'].append('5/1/2013')
        ddict['TestTypeName'].append('MCAS ELA'); ddict['TestTypeName'].append('MCAS Math')
        ddict['TestSubjectName'].append('ELA'); ddict['TestSubjectName'].append('Math')
    else:
        ddict['TestDate'].append('6/1/2013')
        ddict['TestTypeName'].append('MCAS Science')
        ddict['TestSubjectName'].append('Science')

# define function for casting the Performance Levels for MCAS scores
def performance_level_casting(col_value):
    if (col_value == 'F'):
        ddict['Score1Value'].append('1-F')
    elif (col_value == 'W'):
        ddict['Score1Value'].append('2-W')
    elif (col_value == 'NI'):                      # define function for mapping performance levels
        ddict['Score1Value'].append('3-NI')
    elif (col_value == 'P'):
        ddict['Score1Value'].append('4-P')
    elif (col_value == 'A'):
        ddict['Score1Value'].append('5-A')
    else:
        ddict['Score1Value'].append('6-P+')

### Use a for loop to populate the aforementioned lists
This cell is where the majority of the work on this project takes place. Each list in the data dictionary is populated with appropriate values from the sample DataFrame that was imported.

In [66]:
for i in range(0,len(sample)):
    if (sample['grade'][i] == 5) | (sample['grade'][i] == 8) | (sample['grade'][i] == 10):
        for k in range(0,3):
            ddict['NCESID'].append(id_NCESID(sample['district'][i]))
            ddict['StudentTestID'].append(sample['sasid'][i])
            ddict['StudentLocalID'].append('Missing')
            ddict['StudentGradeLevel'].append(sample['grade'][i])
            ddict['TestName'].append('MCAS')
            ddict['TestGradeLevel'].append(sample['stugrade'][i])
        get_TestDate_TestTypeName_TestSubjectName(3)  # Function accounts for TestDate, TestTypeName, and TestSubjectName
        ###      APPENDS ENGLISH MCAS SCORES    ###
        if (sample['eperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # ELA PERFORMANCE SCORES
            performance_level_casting(sample['eperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['escaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # ELA SCALED SCORES
            ddict['Score2Value'].append(sample['escaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['ecpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # ELA CPI SCORES
            ddict['Score3Value'].append(sample['ecpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values
        ###      APPENDS MATH MCAS SCORES    ###
        if (sample['mperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # MATH PERFORMANCE SCORES
            performance_level_casting(sample['mperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['mscaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # MATH SCALED SCORES
            ddict['Score2Value'].append(sample['mscaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['mcpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # MATH CPI SCORES
            ddict['Score3Value'].append(sample['mcpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values
        ###      APPENDS SCIENCE MCAS SCORES    ###
        if (sample['sperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # SCIENCE PERF SCORES
            performance_level_casting(sample['sperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['sscaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # SCIENCE SCALED SCORES
            ddict['Score2Value'].append(sample['sscaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['scpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # SCIENCE CPI SCORES
            ddict['Score3Value'].append(sample['scpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values
            
    elif (sample['grade'][i] == 3) | (sample['grade'][i] == 4) | (sample['grade'][i] == 6) | (sample['grade'][i] == 7):
        for l in range(0,2):
            ddict['NCESID'].append(id_NCESID(sample['district'][i]))
            ddict['StudentTestID'].append(sample['sasid'][i])
            ddict['StudentLocalID'].append('Missing')
            ddict['StudentGradeLevel'].append(sample['grade'][i])
            ddict['TestName'].append('MCAS')
            ddict['TestGradeLevel'].append(sample['stugrade'][i])
        get_TestDate_TestTypeName_TestSubjectName(2)  # Function accounts for TestDate, TestTypeName, and TestSubjectName
        ###      APPENDS ENGLISH MCAS SCORES    ###
        if (sample['eperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # ELA PERFORMANCE SCORES
            performance_level_casting(sample['eperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['escaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # ELA SCALED SCORES
            ddict['Score2Value'].append(sample['escaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['ecpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # ELA CPI SCORES
            ddict['Score3Value'].append(sample['ecpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values
        ###      APPENDS MATH MCAS SCORES    ###
        if (sample['mperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # MATH PERFORMANCE SCORES
            performance_level_casting(sample['mperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['mscaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # MATH SCALED SCORES
            ddict['Score2Value'].append(sample['mscaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['mcpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # MATH CPI SCORES
            ddict['Score3Value'].append(sample['mcpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values
        
    elif (sample['grade'][i] == 9):
        ddict['NCESID'].append(id_NCESID(sample['district'][i]))
        ddict['StudentTestID'].append(sample['sasid'][i])
        ddict['StudentLocalID'].append('Missing')
        ddict['StudentGradeLevel'].append(sample['grade'][i])
        ddict['TestName'].append('MCAS')
        ddict['TestGradeLevel'].append(sample['stugrade'][i])
        get_TestDate_TestTypeName_TestSubjectName(1)  # Function accounts for TestDate, TestTypeName, and TestSubjectName
        ###      APPENDS SCIENCE MCAS SCORES    ###
        if (sample['sperf2'][i] != ' '):
            ddict['Score1Label'].append('Performance Level'); ddict['Score1Type'].append('Level')      # SCIENCE PERF SCORES
            performance_level_casting(sample['sperf2'][i])
        else:
            ddict['Score1Label'].append(' '); ddict['Score1Type'].append(' '); ddict['Score1Value'].append(' ')   # empty values
        if (sample['sscaleds'][i] != ' '):
            ddict['Score2Label'].append('Scaled Score'); ddict['Score2Type'].append('Scale')           # SCIENCE SCALED SCORES
            ddict['Score2Value'].append(sample['sscaleds'][i])
        else:
            ddict['Score2Label'].append(' '); ddict['Score2Type'].append(' '); ddict['Score2Value'].append(' ')   # empty values
        if (sample['scpi'][i] != ' '):
            ddict['Score3Label'].append('CPI'); ddict['Score3Type'].append('Scale')                   # SCIENCE CPI SCORES
            ddict['Score3Value'].append(sample['scpi'][i])
        else:
            ddict['Score3Label'].append(' '); ddict['Score3Type'].append(' '); ddict['Score3Value'].append(' ')   # empty values

In [67]:
x = 0; y = 0; z = 0
for i in range(0,len(sample)):
    if (sample['grade'][i] == 5) | (sample['grade'][i] == 8) | (sample['grade'][i] == 10):
        x = x + 1
    elif (sample['grade'][i] == 3) | (sample['grade'][i] == 4) | (sample['grade'][i] == 6) | (sample['grade'][i] == 7):
        y = y + 1
    elif (sample['grade'][i] == 9):
        z = z + 1
        
print(3*x+2*y+z)

6411

### Create the processed DataFrame
Now that all our data is housed in our data dictionary, we can finally create the processed DataFrame. We can do this by using the Dataframe.from_dict function. Then, all that remains is to reorder the columns so that our DataFrame is formatted properly.

In [68]:
processed = pd.DataFrame.from_dict(ddict)
processed = processed[['NCESID','StudentTestID','StudentLocalID','StudentGradeLevel','TestDate','TestName','TestTypeName',
                       'TestSubjectName','TestGradeLevel','Score1Label','Score1Type','Score1Value','Score2Label','Score2Type',
                       'Score2Value','Score3Label','Score3Type','Score3Value']]     # reorder columns
len(processed)

6411

### END RESULT
We can now display our processed DataFrame below. This shows how the lists have been appended together to form our end result, which is in the form of the “sample-mcas-processed.csv” file, as desired.

In [69]:
# Display the first 10 rows in the processed DataFrame
processed.head(10)

,NCESID,StudentTestID,StudentLocalID,StudentGradeLevel,TestDate,TestName,TestTypeName,TestSubjectName,TestGradeLevel,Score1Label,Score1Type,Score1Value,Score2Label,Score2Type,Score2Value,Score3Label,Score3Type,Score3Value
0,101010,1408905,Missing,3,4/1/2013,MCAS,MCAS ELA,ELA,3,Performance Level,Level,2-W,Scaled Score,Scale,216,CPI,Scale,25
1,101010,1408905,Missing,3,5/1/2013,MCAS,MCAS Math,Math,3,Performance Level,Level,2-W,Scaled Score,Scale,210,CPI,Scale,25
2,101010,1020285,Missing,3,4/1/2013,MCAS,MCAS ELA,ELA,3,Performance Level,Level,3-NI,Scaled Score,Scale,238,CPI,Scale,75
3,101010,1020285,Missing,3,5/1/2013,MCAS,MCAS Math,Math,3,Performance Level,Level,4-P,Scaled Score,Scale,244,CPI,Scale,100
4,101010,1681155,Missing,3,4/1/2013,MCAS,MCAS ELA,ELA,3,Performance Level,Level,3-NI,Scaled Score,Scale,220,CPI,Scale,50
5,101010,1681155,Missing,3,5/1/2013,MCAS,MCAS Math,Math,3,Performance Level,Level,3-NI,Scaled Score,Scale,236,CPI,Scale,75
6,101010,1987801,Missing,3,4/1/2013,MCAS,MCAS ELA,ELA,3,Performance Level,Level,4-P,Scaled Score,Scale,252,CPI,Scale,100
7,101010,1987801,Missing,3,5/1/2013,MCAS,MCAS Math,Math,3,Performance Level,Level,4-P,Scaled Score,Scale,246,CPI,Scale,100
8,101010,1351732,Missing,3,4/1/2013,MCAS,MCAS ELA,ELA,3,Performance Level,Level,4-P,Scaled Score,Scale,246,CPI,Scale,100
9,101010,1351732,Missing,3,5/1/2013,MCAS,MCAS Math,Math,3,Performance Level,Level,3-NI,Scaled Score,Scale,228,CPI,Scale,50

### Write the processed DataFrame into a .CSV file
The last step in this project is to use the pandas to_csv function to save our completed DataFrame file as an Excel .CSV file.

In [ ]:
processed.to_csv(path_or_buf="MTH420 Term Project.csv")